apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gpu-mutating-webhook-deployment
  namespace: gpu-mutating
  labels:
    app: gpu-mutating
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gpu-mutating
    spec:
      containers:
        - name: gpu-mutating
          image: takmatsu/gpu-mutating-webhook:v1.0.1
          imagePullPolicy: IfNotPresent
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: gpu-mutating-webhook-certs
