apiVersion: v1
kind: Service
metadata:
  name: gpu-mutating-webhook-svc
  namespace: gpu-mutating
  labels:
    app: gpu-mutating
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: gpu-mutating
